"""empty message

Revision ID: cbc18782618a
Revises: 
Create Date: 2022-10-31 10:13:12.180951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc18782618a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreaccesorio', sa.String(length=250), nullable=True),
    sa.Column('marca', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consolas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('juego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombrejuego', sa.String(length=250), nullable=True),
    sa.Column('genero', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreproveedor', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refaccion', sa.String(length=250), nullable=True),
    sa.Column('marca', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refacciones')
    op.drop_table('proveedor')
    op.drop_table('juego')
    op.drop_table('consolas')
    op.drop_table('accesorios')
    # ### end Alembic commands ###
